# Generated by Django 5.2 on 2025-07-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigfilestore',
            name='file_name',
            field=models.CharField(default='', help_text='The name of the file', max_length=1000),
        ),
        migrations.AddField(
            model_name='bigfilestore',
            name='mime_type',
            field=models.CharField(default='', help_text='The mimetype of the file', max_length=1000),
        ),
    ]
