# Generated by Django 5.2 on 2025-07-28 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_file_organization_file_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='ocr_engine',
        ),
        migrations.RemoveField(
            model_name='document',
            name='page_count',
        ),
        migrations.RemoveField(
            model_name='page',
            name='preprocessor_config',
        ),
        migrations.RemoveField(
            model_name='page',
            name='rotation_angle',
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.bigfilestore'),
            preserve_default=False,
        ),
    ]
